### ISSUE TITLE
weui应用案例登记

### ISSUE THREAD

**Issue by zhoudaqing** [Tencent/weui#181]
请问有哪些产品在使用weui欢迎登记

**Comment by AmMRLi** [comment]
我的微信和QQ公众号“诗词文学”都在使用。诗词文学微信已经上了V1版本，目前正在进行V2的调整。因为只能在微信内打开，也没弄demo，所以没示例的URL。完整的截图已经按照@jf 的要求，上传在WeUI的QQ群文件里了。

【诗词文学】
专注古典诗词，鼓励原创文学。做传统文化的传承和传播者。

![qq -](https://cloud.githubusercontent.com/assets/16911415/12619731/5a36c8aa-c554-11e5-9b1c-6943bcfc35c2.png)
![weui-screen-1 0- 03](https://cloud.githubusercontent.com/assets/16911415/12619771/83db73e0-c554-11e5-8341-c0c0716ad187.png)
![weui-screen-1 0- 08](https://cloud.githubusercontent.com/assets/16911415/12619773/83dbe690-c554-11e5-8932-7470a37e407f.png)
![weui-screen-1 0- 11](https://cloud.githubusercontent.com/assets/16911415/12619772/83dbaf4a-c554-11e5-989f-08b679c603de.png)
![weui-screen-1 0- 12](https://cloud.githubusercontent.com/assets/16911415/12619774/83df6ef0-c554-11e5-8941-f6bdba24126e.png)
![weui-screen-1 1 0- 02](https://cloud.githubusercontent.com/assets/16911415/12619775/83dfcfbc-c554-11e5-9fdf-e9179d8a8b94.png)
![weui-screen-1 1 3- 03](https://cloud.githubusercontent.com/assets/16911415/12619776/83e120b0-c554-11e5-9e4f-cf25752a9835.png)
![weui-screen-1 1 4- 02](https://cloud.githubusercontent.com/assets/16911415/12619779/8414d3e2-c554-11e5-935e-cb7253f3cb53.png)
![weui-screen-1 1 6- 02](https://cloud.githubusercontent.com/assets/16911415/12619777/840cd91c-c554-11e5-8e6a-852cc72256b4.png)
![weui-screen-1 1 9- 07](https://cloud.githubusercontent.com/assets/16911415/12619778/84119ae2-c554-11e5-9ea7-4cade61c7678.png)

**Comment by progrape** [comment]
:+1:

**Comment by jf** [comment]
Hello @AmMRLi , I am **not** involved in this at all. Do you have proof that I actually requested this as you claim? I'll need to know if this actually happened.

**Comment by yarving** [comment]
能提供下使用weui的源码借鉴下吗？

**Comment by baixuer2013** [comment]
同意楼上，好像看到开发者的样式版图和源码参考一下。

**Comment by baixuer2013** [comment]
同意楼上，好想看到开发者的样式版图和源码参考一下。

**Comment by zhanweixin** [comment]
由厦门睿科特与厦门大学共同面向行业客户提供物联网应用的综合性服务平台"倍安卫士”即将上线，它也是基于weui开发的典型案例。
    关注“倍安卫士”请长按或扫描如下二维码
![倍安卫士服务号](http://www.4001168908.com/bgwx/img/beaan_qrcode.jpg)

    
![服务中心](http://www.4001168908.com/bgwx/img/fwzx.png)

![设备在线测控](http://www.4001168908.com/bgwx/img/zxcz.png)

![终端分组管理](http://www.4001168908.com/bgwx/img/zqsq.png)

![终端权限管理](http://www.4001168908.com/bgwx/img/qxgl.png)

![单位管理](http://www.4001168908.com/bgwx/img/dwgl.png)

![单位职工管理](http://www.4001168908.com/bgwx/img/zggl.png)

**Comment by vangogogo** [comment]
不错啊

**Comment by logoove** [comment]
http://weixin.yoby123.cn/weui/ 参考我写的

**Comment by Javen205** [comment]
@logoove  http://weixin.yoby123.cn/weui/ 你这个样式 目前还是开源的吗？ 有详细的使用介绍吗？

**Comment by logoove** [comment]
@Javen205    当然是开源的  到我的主页去打包下载  使用方法参考源码

**Comment by Wscats** [comment]
[基于angular.js,weui和node.js重写的新闻客户端](https://github.com/Wscats/Angular-news)

**Comment by cipchk** [comment]
[ngx-weui](https://cipchk.github.io/ngx-weui/)
