### ISSUE TITLE
请问如何使用到真实的生产环境中去？

### ISSUE THREAD

**Issue by leebin17** [Tencent/weui#28]
我想要这样的效果，希望在微信公众号项目中能使用。
那我改怎么做呢？

我通过开发环境去开发出了我想要的效果之后，如何提取这些html/css/js，使用到真实的微信公众号项目中呢？
需要部署微信公众号项目的服务器有
nodejs？还是怎么样能不能给小弟指点一番

**Comment by uxsi** [comment]
weui本身只是一个UI库，最后输出的核心是[weui.css](https://github.com/Tencent/weui/wiki/getting-started)，dom需要开发者自行拷贝到本地
