### ISSUE TITLE
微信用户属性

### ISSUE THREAD

**Issue by zjhui** [Tencent/weui#524]
https://github.com/weui/weui/wiki/%E5%BE%AE%E4%BF%A1%E7%94%A8%E6%88%B7%E5%B1%9E%E6%80%A7
这个页面里面的数据有最新的吗。现在还是2015年的，对现在来说没有参考意义了。有最新数据的话希望能更新一下，给我们做个参考。

**Comment by BearJ** [comment]
@zjhui 好的，我们近期会做出更新

**Comment by zjhui** [comment]
看了下，IOS9，IOS10似乎都没统计进去。
