### ISSUE TITLE
window.pageManager.go存在bug，拿官方提供的Demo做在线演示

### ISSUE THREAD

**Issue by aiyuchen** [Tencent/weui#563]
chrome打开https://weui.io      ，启动调试工具按照移动端的方式查看
找到
```
<script type="text/html" id="tpl_list">
```
将
```
<h1 class="page__title">List</h1>
// 修改HTML为
<h1 class="page__title"><a href="javascript:window.pageManager.go('home');" class="">List</a></h1>
```

找到
```
<script type="text/html" id="tpl_input">
```
将
```
<h1 class="page__title">Input</h1>
// 修改HTML为
<h1 class="page__title"><a href="javascript:window.pageManager.go('list');" class="">Input</a></h1>
```

问题：
OK，现在可以在【首页】、【列表】页面、【表单】页面，来回点击切换，点击次数不用超过3次，你会发现，页面乱了，本该进入首页的，进入列表页了，或者是本该进入列表页的，进入首页了。。。。。

我是没搞明白这是什么问题，求助有谁懂，怎么解决

**Comment by aiyuchen** [comment]
我好想知道问题所在了，首先监听了一个windows事件
```
$(window).on('hashchange', function () {
```

然后在这里找出堆栈的对象，执行了`_back`这个方法
```
if (state._pageIndex <= self._pageIndex || self._findInStack(url)) {
    self._back(page);
```

在`_back`这个方法中，先将当前页面在堆栈中弹出去
```
var stack = this._pageStack.pop();
// .....
stack.dom.addClass('slideOut').on('animationend webkitAnimationEnd', function () {
    stack.dom.remove();
});
```

那么问题就来了，如果我切换了2个页面（加上初始页面，就是3个页面）；弹出去最后一个页面，那第二个页面还在第一个页面上覆盖着。。。。。

这样就造成了看到的页面不正确了。。。。。求解决办法

**Comment by aiyuchen** [comment]
我是这样解决的，目前还没有发现有问题，不知道有没有更好的方法
```
// 修改_back 方法
if (!found) {
    // 这里保持和官方写的代码不变，增加一个ELSE
} else {
    for (var i = 0, l = this._pageStack.length; i < l; i++) {
        if (this._pageStack[i].config.url != url) {
            this._pageStack[i].dom.remove();
            this._pageStack.splice(i, 1);
        }
    }
}
```

**Comment by aiyuchen** [comment]
纠正下问题，这个不是window.pageManager.go 的错误，就算不使用window.pageManager.go，直接这样写
```
<a href="#page">...</a>
```
只要跳转的页面大于2，一样存在问题。目前我使用上面的方法解决了

**Comment by aiyuchen** [comment]
重新优化了一下，应该这样比较合理。如果找到了之前的页面，而这个页面并非当前页面下一层，就一层一层的删除
```
if (!found) {
    // 这里保持和官方写的代码不变，增加一个ELSE
} else {
                for(var i = this._pageStack.length - 1; i > 0; --i) {
                    if (!this._pageStack[i]) {
                        continue;
                    }

                    this._pageIndex--;
                    if (this._pageStack[i].config.url == url) {
                        break;
                    }

                    this._pageStack[i].dom.remove();
                    this._pageStack.splice(i, 1);
                }
}
```

**Comment by BearJ** [comment]
@aiyuchen 亲，example只是做demo用，所以代码没有那么严谨，请见谅哈。

**Comment by zxui** [comment]
@aiyuchen @BearJ 是的，我也遇到这个问题了，这个路由有问题

**Comment by billschen** [comment]
个人认为，不应该将weui.io的首页做得那么复杂，次给页面的实现直接上HTML就可以了，现在页面搞成js的，增加了入门难度。
分成向个页面就好了。毕竟weui是用于页面的。

**Comment by hanchun776** [comment]
腾讯的东西从来都是这样一副你爱用不用的态度

**Comment by BearJ** [comment]
@zxui 你可以看看这里，有很多很好的路由库：https://github.com/sorrycc/awesome-javascript#routing

**Comment by BearJ** [comment]
@billschen example.js这个是为了提高用户体验而写的，并不属于weui的标准库。这点相信大家能理解。

**Comment by dusdong** [comment]
@BearJ 用户更大的期望是有一个开箱即用的 example  ^_^

**Comment by zxui** [comment]
@BearJ 嗯  谢谢！缺点是不可避免的，但已经算是不错了，期待继续更新完善

**Comment by PHPJourney** [comment]
我差点跑去react-weui提问。我也碰到这个路由问题。表示它好像把每个模板都载入到静态内部变量当中了。并且只是append 没有进行去重操作。多次点击操作后，路由完全乱了。你们谁有解决好的么。因为我刚刚给example增加了语言包业务。路由方面没有进行处理。
另外在touch事件当中，之前开发过程中碰到与第三方库冲突，搜索uc浏览器的解决方案发现他们的touch业务并不是在touchend就结束了，真正的结束点在touchcancel。同时weui没有提供touch轮播图片的代码。这个比较操蛋。

**Comment by PHPJourney** [comment]
@aiyuchen 你在如何处理页面的惯用模板。如果每个页签都要替换头部标题，从哪里提取合理点。异步读取还是直接$(this).text()

**Comment by chaozh** [comment]
感觉这种页面切换是个比较简单的需求，不知道能不能归纳为一个小工具库
