### ISSUE TITLE
ie9的错误比较多，有没有针对性的条件匹配css做修正？

### ISSUE THREAD

**Issue by sidealice** [Tencent/weui#568]
ie6~ie8还可以不考虑，因为ie9是xp不支持以后推出的。所以不匹配的话，pc访问效果就大打折扣了。
如果考虑文件尺寸，可以做个条件css我们放在最后加载。 我们目前遇到的问题主要是底部的tab

**Comment by BearJ** [comment]
@sidealice 你好，weui主要是针对移动端页面而开发的，IE可能暂时不做考虑。

**Comment by gaoqiang19514** [comment]
哈哈，本来就是移动端的，这人怎么搞到ie上去了，服！

**Comment by sidealice** [comment]
down grade的效果是能够不影响访问，我觉得不支持ie不要紧，但是在用ie访问时候不会受到影响也很关键。 

如果是纯移动端，目前的css也只是依赖了webkit ， 没有考虑到opera，firefox的情景， ie也有手机浏览器。 如果可以还是兼容性明确下版本。最差能够方便我们看到哪些用了内核特性，便于写css hack进行修正。

**Comment by BearJ** [comment]
@sidealice 好的，这里是应该给一下兼容列表。后续我们会补上
