### ISSUE TITLE
wkwebview input输入框被遮挡

### ISSUE THREAD

**Issue by cococe** [Tencent/weui#577]
微信iOS客户端将于2017年3月1日前逐步升级为WKWebview内核。
经测试发现。document.activeElement.scrollIntoViewIfNeeded解决input输入框被遮挡失效。
可用document.activeElement.scrollIntoView代替实现该功能。

测试环境：
iphone7plus128G 版本10.2(14c92)
微信版本6.5.3

**Comment by BearJ** [comment]
好的，谢谢建议，但那个方法是android使用的哟。。。IOS我们并没有针对这个做出处理。
