### ISSUE TITLE
微信端侧滑返回bug 

### ISSUE THREAD

**Issue by qingdie** [Tencent/weui#588]
我反复测试发现，连续打开3个窗口后，侧滑返回只能两次，在第3个窗口侧滑时看到的是第一个窗口的图像，侧滑完成后页面突然变成了第二个窗口，再次侧滑页面关闭了，应该是返回第一个窗口。
从第3个窗口侧滑返回到第二个窗口时，再侧滑没有了，但是顶上返回键点击有效。
点击顶上的返回按钮就一切都正常！

**Comment by BearJ** [comment]
@qingdie 试试最新版的微信？
