### ISSUE TITLE
pc版微信客户端中SPA项目 pushState改变url不起作用

### ISSUE THREAD

**Issue by fisherw** [Tencent/weui#591]
使用React-router作单页面路由，用pushState的方式更改url，页面能正常切换（a页面->b页面），但在b页面没有回退按钮，复制链接仍然是a页面的链接，在b页面刷新页面才能出回退按钮（然后复制链接还是a页面链接）

貌似使用hash也是一样，pc微信客户端这个坑有什么解决方案吗（我不想每个路由都刷新）

**Comment by BearJ** [comment]
@fisherw 好的，这个我帮你转告给相关负责人哈~

**Comment by 429365799** [comment]
同问，手机端的微信页面没问题，就是windows上面的微信浏览器有这个问题

**Comment by shanda506365** [comment]
这个问题还没解决吗？

**Comment by myhelloos** [comment]
ios上也有同样的问题

**Comment by szwork2013** [comment]
万恶的微信 不同版本抽风性的不支持 history.pushState

**Comment by billschen** [comment]
去  [react-router v4.0 ](https://reacttraining.com/react-router/web/guides/philosophy) 
做是没有问题的。

**Comment by MiracleRo** [comment]
麻烦问一下这个问题什么时候可以解决呢  现在ios 和pc的微信仍然存在这样的问题

**Comment by bruceCzK** [comment]
#125

**Comment by windhc** [comment]
直至2018-11-16, 问题还没解决

**Comment by windhc** [comment]
直至2018-11-17, 问题还没解决
