### ISSUE TITLE
演示网页在微信内置的浏览器里不工作

### ISSUE THREAD

**Issue by lilac** [Tencent/weui#597]
在安卓版微信打码打开演示页面，其上传案例中，点添加按键无反应。
但是Chrome在浏览器中打开正常。
另外，微信中打开React-weui项目的上传演示页，其添加功能也正常。

**Comment by BearJ** [comment]
@lilac 我对比了一下，区别就是演示页的input多了`multiple`的属性，这个属性是用于允许多选图片的，如果你那边有问题，你可以把这个属性去掉看看？

**Comment by qinghechaoge** [comment]
multiple属性 去掉后 vivo手机可以选择图片了
但是点击完图片 没有反应
