### ISSUE TITLE
Input 的实例代码报错

### ISSUE THREAD

**Issue by PeiwenYu2** [Tencent/weui#598]
你好，貌似缺少input的end-tag，<input type="radio" class="weui-check" name="radio1" id="x11"/> 加了‘／’后可以成功编译。是实例代码有误吗？

**Comment by BearJ** [comment]
这个的确可以优化~

**Comment by BearJ** [comment]
您好，这个应该是和你的编译工具有关，现在不建议在end-tag加入 / 了。详情可见：https://github.com/whatwg/html/blob/master/FAQ.md#should-i-close-empty-elements-with--or-
