### ISSUE TITLE
如何滑动到顶部或底部时，不出现黑底

### ISSUE THREAD

**Issue by NotGeekAtAll** [Tencent/weui#605]
weui的demo在微信中浏览时，不论在顶部和底部如何滑动，都不会拉出黑色的部分(就是网页由xxx提供那部分)，我按照demo外层一个div，设置position:absolute;overflow:hidden。然后里面一个div设置position:absolute;overflow-y:auto。滑动还是会有黑色部分出现，请问weui的demo是用js控制了吗。

**Comment by BearJ** [comment]
@NotGeekAtAll 是的，直接用jsAPI，不过这个API目前尚未对外开放

**Comment by wenguangcheng** [comment]
求告知应该处理!!!

**Comment by BearJ** [comment]
@wenguangcheng 因为是涉及到页面安全，这个api还未能对外~请谅解哈
