### ISSUE TITLE
1.1.1 demo 部分组建不显示的问题

### ISSUE THREAD

**Issue by piaohan** [Tencent/weui#607]
panel 组件 不可点击 没有效果

**Comment by billschen** [comment]
这些描述实在太简单了，根本没有办法分析你的问题~

**Comment by piaohan** [comment]
可以了

**Comment by piaohan** [comment]
我说的就是 demo 页面 panel 组件不可点击

**Comment by piaohan** [comment]
https://weui.io

![snip20170330_1](https://cloud.githubusercontent.com/assets/12056081/24483954/1a1897be-152e-11e7-8357-36718f5085ce.jpg)

我只想给你提交个问题，你却让我关闭。

**Comment by BearJ** [comment]
@piaohan 估计是你的窗口发生了改变导致的，这时候你只要在刷新一下页面即可。因为是页面加载时会用js判断底部是否要absolute~

**Comment by piaohan** [comment]
@BearJ 刷新是解决不了的,所以我想来提交下,移动端不会有次问题,此问题只出现macPC页面端,您有机会可以尝试下.

**Comment by BearJ** [comment]
@piaohan 用mac的safari试了下，好像没问题呀。。刷新一下就可以了。。

**Comment by ygwoo** [comment]
Windows下Chrome似乎也有这个问题

**Comment by BearJ** [comment]
@ygwoo 刷新之后呢？

**Comment by Fifth-Patient** [comment]
同样发现这个问题，使用uBlock过滤掉元素了。

**Comment by ygwoo** [comment]
@BearJ 刚刚又试了下，刷新后问题同样还存在。 Windows 下 Chrome 63.0.3218.0 x64
