### ISSUE TITLE
Picker 中dataPicker 设置默认值的问题

### ISSUE THREAD

**Issue by zengjun24** [Tencent/weui#609]
如何设置默认时间？

**Comment by BearJ** [comment]
@zengjun24 https://github.com/weui/weui.js/blob/master/docs/component/picker.md

**Comment by longweilol** [comment]
你说的这个属性defaultValue没有反应呀

**Comment by BearJ** [comment]
@longweilol 你是如何调用的？

**Comment by progrape** [comment]
@longweilol 提供一下调用代码？

**Comment by VincentZee** [comment]
@progrape 
我用的v0.1.5版本
代码如下：
         $('#showDatePicker').on('click', function () {
	        weui.datePicker({
			    start: 1990,
			    end: 2000,
			    defaultValue: [1991, 6, 9],
			    onChange: function(result){
			        console.log(result);
			    },
			    onConfirm: function(result){
			        console.log(result);
			    },
			    id: 'datePicker'
			})
	    });

结果如下：
![image](https://user-images.githubusercontent.com/10300118/27425605-86959f48-576b-11e7-8534-dbbef9af0b8a.png)

**Comment by VincentZee** [comment]
@progrape 不过v1.1.1版本试了下，设置默认值正常。可能 @zengjun24 用的版本不是最新的

**Comment by ningyuv** [comment]
可能因为设置了id
`id: 'datePicker'`
