### ISSUE TITLE
wiki demo code doesn't work

### ISSUE THREAD

**Issue by 1213042026** [Tencent/weui#610]
https://mp.weixin.qq.com/wiki/2/ae9782fb42e47ad79eb7b361c2149d16.html#Dialog
这里面的实例html代码不起作用，调试发现class命名又是中划线又是下划线。
??版本原因？

**Comment by BearJ** [comment]
@1213042026 是的，这个是旧版的wiki，这才是最新版的链接哈~
https://mp.weixin.qq.com/wiki/
