### ISSUE TITLE
使用了背景图的页面出现白框

### ISSUE THREAD

**Issue by xiehailian** [Tencent/weui#615]
我的首页使用了背景图，css的代码是：
`.aix-bg {
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  background-image: url(../img/bg.jpg);
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
  background-size: cover;
  -webkit-background-size: cover;
}`

但是在不同的机型上，进入页面时有的会出现白框，有的不会出现白框，这是怎么回事呢？
如图所示：
[不正常的](http://oj8vattcf.bkt.clouddn.com/%E4%B8%8D%E6%AD%A3%E5%B8%B8%E7%9A%84.jpg)
[正常的](http://oj8vattcf.bkt.clouddn.com/%E6%AD%A3%E5%B8%B8%E7%9A%84.jpg)

**Comment by BearJ** [comment]
@xiehailian 看着有元素挡住了，有没有页面代码可以调试的？
