### ISSUE TITLE
为什么我使用了defaultValue设置没反应

### ISSUE THREAD

**Issue by longweilol** [Tencent/weui#618]
我在 weui.min.js中 找不到defaultValue属性为什么

$('#showDatePicker').on('click', function() {
			weui.datePicker({
				start : 1990,
				end : 2020,
				defaultValue: [2018, 6, 9],
				onChange : function(result) {
					console.log(result);
				},
				onConfirm : function(result) {
					console.log(result);
				}
			});
		});

**Comment by BearJ** [comment]
@longweilol 最新版的weui.js: https://res.wx.qq.com/open/libs/weuijs/1.1.1/weui.min.js
