### ISSUE TITLE
weui在table表格中用a标签跳转链接，在移动端点击为什么无效

### ISSUE THREAD

**Issue by sunqisoftware** [Tencent/weui#620]
weui在table表格中用a标签跳转链接，在移动端点击为什么无效
/*
<table class="weui-table weui-border-tb">
                <thead>
                <tr><th>已购买</th><th>状态</th><th>会员到期时间</th></tr>
                </thead>
                <tbody>
                <tr><td>2014257777</td><td>使用中</td><td>2016-02-06</td></tr>
                <tr><td>2014257777</td><td>待付款</td><td><a href="http://www.baidu.com">付款</a></td></tr>
                <tr><td>2014257777</td><td>待付款</td><td><a href="http://www.baidu.com">付款</a></td></tr>
                </tbody>
            </table>
*/
咱们的官方样例，在pc端可以正常访问，但是在手机端，点击付款标签无法跳转，是兼容原因么？

**Comment by logoove** [comment]
加到 td上面 click a的确不起作用 好像点击事件被阻止了

**Comment by BearJ** [comment]
@sunqisoftware 试试给body加个ontouchstart的属性？
