### ISSUE TITLE
[iOS][SearchBar]使用输入法的退格删除搜索词，光标不回到开头

### ISSUE THREAD

**Issue by skynewborn** [Tencent/weui#630]
![image](https://cloud.githubusercontent.com/assets/1468857/25799372/50d3b7a4-3417-11e7-965b-4dd78b85e3da.png)
如附图所示。使用退格键删除最后一个字时，光标并未回到开头，而是空了一个字符的位置。再次按键才能回到开头。
版本：1.1.2

**Comment by BearJ** [comment]
@skynewborn 感觉不是样式的问题，试试每次inputchange打印value出来看看？

**Comment by skynewborn** [comment]
https://weui.io
官方demo可复现。
iPhone 6p，iOS 10.3.3，微信版本6.5.15。
