### ISSUE TITLE
https://weui.io/ demo页面在chromium 58.0.3029.81 上无法使用

### ISSUE THREAD

**Issue by sgon00** [Tencent/weui#632]
如题。我尝试了 react-weui 的demo页面 https://weui.github.io/react-weui, chromium使用是没问题的。
但是非react的 https://weui.io/ ，打开后，点任何按钮都没反映。虽然说这个是专门为微信内置浏览器开发的。是不是最起码桌面chrome可以点一点才对呀？谢谢您。

**Comment by BearJ** [comment]
@sgon00 我试了下，没问题。。？你看看是否有报错？

**Comment by billschen** [comment]
@sgon00 
我这里表现得很好。
