### ISSUE TITLE
触发事件会出现两次

### ISSUE THREAD

**Issue by ChinaDragonHunter** [Tencent/weui#635]
并没有引用example.js。使用weui和weui.js的时候，当我点击时，会出现两次点击操作，下拉框也出现了值重复问题，同时调用了两次请求，例如：http://www.titanlegend.com/mars/toolkit/ 模拟请求tab页，点击模拟请求的tab页面，我会请求ajax，但是会请求两次，造成值重复。

**Comment by BearJ** [comment]
weui.js用的是click事件，是不是其它地方用了tap，导致点击穿透了？
