### ISSUE TITLE
内置对象WeixinJSBridge以后不再维护了吗？

### ISSUE THREAD

**Issue by aDaiCode** [Tencent/weui#638]
打开wiki里给出的 “微信JS-SDK说明文档” 链接(https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141115&token=&lang=zh_CN)；
在该文档下，并没有关于WeixinJSBridge的介绍，而是关于jweixin-1.2.0.js的介绍。

以后WeixinJSBridge对象不再继续维护了么？

**Comment by progrape** [comment]
@aDaiCode `WeixinJSBridge` 是底层的接口，建议使用官方封装的 jssdk，也就是你看到的 jweixin-1.2.0.js 的介绍。
