### ISSUE TITLE
vue下uploader的问题

### ISSUE THREAD

**Issue by lgd8981289** [Tencent/weui#644]
在webpack+vue-cli创建的应用 ， 使用weui中的uploader功能模块，无法调用系统选择图片的功能。在onChange下无法获取事件，在click下获取event为undefined
代码如下：
<div class="weui-cell" >
                <div class="weui-cell__bd">
                  <div class="weui-uploader">
                      <div class="weui-uploader__input-box">
                        <input id="uploaderInput" class="weui-uploader__input"
                               type="file" accept="image/*" multiple="true"
                               v-on:change="onUpLoaderClick($event, item)"/>
                      </div>
                    </div>
                  </div>
                </div>

onUpLoaderClick: function (event, item) {
        var files = event.target.files;
        var url = window.URL || window.webkitURL || window.mozURL;
        var fileSrc = null;
        for (var i = 0; i < files.length; i++) {
          var file = files[i];
          if (url) {
            fileSrc = url.createObjectURL(file);
          } else {
            fileSrc = e.target.result;
          }
          file.fileSrc = fileSrc;
        }
      }

**Comment by BearJ** [comment]
@lgd8981289 “无法调用系统选择图片的功能”，请问这时input的属性`accept="image/*"` 吗？
