### ISSUE TITLE
weui有轮播图吗？

### ISSUE THREAD

**Issue by avocadowang** [Tencent/weui#647]
看demo是没有，有没有官方的轮播？只能引入第三方？

**Comment by progrape** [comment]
轮播图推荐使用 http://idangero.us/swiper

**Comment by zhangolve** [comment]
我这个1.0.2版本的react-weui，看源码是有轮播图(swiper)的，但是没有看到demo。

**Comment by BearJ** [comment]
@zhangolve 可以去react-weui那里提个issue哈

**Comment by billschen** [comment]
react-weui不是weui的儿子吗？儿子有的东西，父亲没有?
