### ISSUE TITLE
pc上直接调用怎么老是提示有有安全隐患呢？

### ISSUE THREAD

**Issue by simonkong** [Tencent/weui#651]
将这个代码下载到本地，放入apache配置的环境里面，直接在浏览器里调用examlple/index.html，浏览器会提示“网页不安全”，难道代码里有后门？

**Comment by BearJ** [comment]
@simonkong 这貌似不是我们的问题吧。。应该是apache的配置，或者你页面的路径，又或者是证书的问题？

**Comment by koran74557** [comment]
有的时候还会提示视频消失

https://user-images.githubusercontent.com/104236719/164826616-feaf9a6d-aa1a-4f48-818f-c79ed5293a72.mp4
