### ISSUE TITLE
表单验证设计有缺陷，只有required的才验证，非必填项难道就不用验证了？

### ISSUE THREAD

**Issue by Zzcaocao** [Tencent/weui#654]

**Comment by BearJ** [comment]
@Zzcaocao 是的，目前的确有优化空间，如果你想非必填但又需要验证，试试填pattern='^$|xxx'  `|`分隔号后面是你要验证的正则表达式

**Comment by Zzcaocao** [comment]
@BearJ 我当然试过了，不行的。因为有required为空时就直接验证失败了，根本不会去通过pattern验证。而不加required的又不做验证。

**Comment by BearJ** [comment]
@ZoomZhao 新版的weui.js可以了，试试？https://res.wx.qq.com/open/libs/weuijs/1.1.2/weui.min.js

**Comment by Zzcaocao** [comment]
赞，可以了
