### ISSUE TITLE
如何：在一个cell中使用多项输入

### ISSUE THREAD

**Issue by billschen** [Tencent/weui#655]
我知道，现在一个cell可以分成
head、 body 、foot三项，正常情况下，一个cell应该中允许输入用户的一项内容的。
这点感觉很好，有区分感，但有时候，用户输入的内容必须挨在一起才感觉良好，例如。
房屋户型，一般的表达形式为：N房N厅N卫。楼宇结果一般表述为 N梯N户。
对于这些内容，我觉得应该是一行输入完整更好。类似于以下图的形式：
![del78](https://user-images.githubusercontent.com/19528399/28743645-57b8d824-7481-11e7-82ce-ace1efe76f2a.png)

**请问：**在使用weui作为我整个界面主要风格不变，样式不变的情况下，有没有什么普通的办法。实现上面的效果？或者，有什么更多的处理方式？
多谢！

**Comment by inroading** [comment]
weui-flex 就可以呀

**Comment by billschen** [comment]
@inroading 多谢！我没有用 weui-flex，用其他方法实现了。效果如下图。
![del_45](https://user-images.githubusercontent.com/19528399/29250491-b2464b82-8075-11e7-8b3b-d02de5d19f20.png)
