### ISSUE TITLE
根据示例做操作反馈，在一个单独的页面上做，页面上的所有元素都显示不出来。

### ISSUE THREAD

**Issue by billschen** [Tencent/weui#656]
@BearJ  我参考：[https://weui.io/#msg_success](https://weui.io/#msg_success)。
将其中的html copy 出来，自己做成一个页面，但结果却什么东西也显示不出来。
如下图所示：
![del_45](https://user-images.githubusercontent.com/19528399/29250533-75eae4f8-8076-11e7-9a21-bf389ec3ccef.png)
为什么会过样呢？

**Comment by BearJ** [comment]
连文本都没有，估计是渲染bug（刷新试试），或者你有一些浮层盖住了它们？

**Comment by qichhhhh** [comment]
给最外层div 加上js_show 
注意看weui.io的示例代码

**Comment by BearJ** [comment]
楼上正解~

**Comment by scottfly189** [comment]
果然，weui的文档真的太差了，一开始就受挫啊
