### ISSUE TITLE
Weui Picker display error sometime

### ISSUE THREAD

**Issue by qzm** [Tencent/weui#657]
Weui Picker display error sometime in android when keyboard show .
Weui的picker在弹出来的时候在Android手机键盘已经弹出来的情况下，有一定概率显示错误。

![evgxwg oxi vmscdbi 7dw](https://user-images.githubusercontent.com/2801450/29257909-3c27c836-80e8-11e7-98e7-ec6722e7c5b4.jpg)

Device:HUAWEI Mate7

**Comment by BearJ** [comment]
@qzm 好的，我们看看

**Comment by qzm** [comment]
hi，我这边问题已经解决，是Android某个webview的问题，与weui无关，这个页面的刷新点和系统滚动缩放的刷新点对在一起，也就是页面高度刚好跟webview差不多的时候，软键盘弹出之后，再点击picker会触发这种问题，解决方案是增加页面高度。 目前测试仅在 Huawei Mate 7 出现问题，其他android手机正常。

**Comment by BearJ** [comment]
好的，那这里先close吧
