### ISSUE TITLE
weui是怎么做手机适配的呢？

### ISSUE THREAD

**Issue by jiafulu** [Tencent/weui#658]
我发现在Chrome调试工具里面不同手机表现差不多，不知道是怎么适配的呢？

**Comment by ydq** [comment]
个人觉得，只要遵循标准的CSS3，绝大多数浏览器都没什么问题，然后针对一些比较冷门的css3属性，参考一下caniuse等网站的支持度情况，遇到用户反馈等再找实体机测试即可。

Chrome的调试工具只是针对不同屏幕的尺寸（屏幕宽高），并不是说不同手机支持的CSS实际显示效果。

毕竟你是按照css3的写法来做的，如果浏览器本身的bug你也无法解决，如果出现问题的浏览器用户量大，你可能就得改写成一些不优雅的其他途径来达到相同的显示效果，或者通知厂商修复bug。就看你的取舍。

**Comment by jiafulu** [comment]
@ydq 谢谢了，
其实我的意思是单位px的问题，只使用px，好像在调试工具里也都是一样的
