### ISSUE TITLE
切换navbar时，页面滚动位移相互影响

### ISSUE THREAD

**Issue by qingshanbugai** [Tencent/weui#659]
在使用navbar时，不同页面的滚动位移相互影响，页面一滚动之后，切换到页面二，页面二滚动到了页面一滚动过的位置，还是说其实滚动的时候是所有页面一起滚动的？
![image](https://user-images.githubusercontent.com/7610726/29350880-e50bd7d4-8292-11e7-822c-a9ed4050f6d8.png)
![image](https://user-images.githubusercontent.com/7610726/29350901-fe22ebe0-8292-11e7-8d3d-ab757c8bfcec.png)

**Comment by BearJ** [comment]
页面其实并没有滚，而是直接刷的。你可以看看代码，直接是hidden掉的

**Comment by KevinHades** [comment]
> 
> 
> 页面其实并没有滚，而是直接刷的。你可以看看代码，直接是hidden掉的

我不太明白，说的直接刷的是什么意思，我也遇到了楼主的问题
