### ISSUE TITLE
比如这个网站qq.com， 其实很多腾讯公司的网站，做的特别差，几百年风格不变。贵公司又天天找人，都找的是什么人啊。市值千亿都没用。

### ISSUE THREAD

**Issue by anlexN** [Tencent/weui#664]
本人纯属出于友善的批判，没有恶意。只是希望腾讯公司能反思一下问题，谢谢。

**Comment by anlexN** [comment]
最基本的就是没有页面自适应，古老的风格

**Comment by airyland** [comment]
![image](https://user-images.githubusercontent.com/559179/29645980-262eb90e-88b3-11e7-9408-289b27cf1201.png)

本人纯属出于友善的批判，没有恶意。只是希望 @anlexN 能反思一下问题，谢谢。

最基本的就是在开源项目下把 issue 当论坛发与项目无关的垃圾信息，愚蠢的行为。

**Comment by afeiship** [comment]
为什么其它的issue回复都很慢，这种却是秒回？

**Comment by anlexN** [comment]
因为有人不开兴了。@airyland, 我被你批评，没关系。请问，你能不能先正视我的问题，解释我的问题，在批评我，行吗？我们礼尚往来，行吗？全球最著名的开源工程linux，都能正确解决所谓的“垃圾信息”，就你们weui开源库，不行。请问，weui开源库能否运用到腾讯旗下网站？

**Comment by CurryHan** [comment]
@anlexN 你好逗,义愤填膺的干嘛。

**Comment by anlexN** [comment]
For tencent, to be a permanent tech company, or not to be, that's a question.....

**Comment by CoderMageFox** [comment]
@anlexN 
满口友善却恶意中伤,是不仁.
在开源社区讨论问题的地方浪费大家的时间,是不义.
没有经过具体的调查分析就下定论,是不智.


不是每个问题都需要被重视的,先问是不是,再问为什么.无端的污蔑并不能显得自己很厉害,反而会让别人厌恶你这样的不仁不义不智之徒.

在GitHub提这种东西,能看到的可不止中国人.

同是前端,为你感到羞耻.

**Comment by dusdong** [comment]
这种问题不适合在这里讨论，关了吧

**Comment by anlexN** [comment]
关了吧，我只是一个五年经验的程序员，个人感受就是weui跟material design，purecss 差距特别大，而且腾讯很多产品之间技术关联度不大。对不起，我不应该批评贵公司，我也没有诽谤之意。纯粹，希望你们能加油。
退一步，海阔天空。忍一时，风平浪静。
如有得罪，多多包涵

**Comment by Luomusha** [comment]
@anlexN 
此人人品有问题，缺乏最基本礼仪和常识。
请不要侮辱五年经验程序员这类人群。

**Comment by YangTianKundream** [comment]
你们真无聊，我邮箱一上午就收你们这些邮件了……

**Comment by YangTianKundream** [comment]
还有发起这个话题的哥们儿，人家鹅厂招人跟你有关系吗？你是不是关心的有点多了？

**Comment by Zzzard** [comment]
老哥把这当论坛了吧.

**Comment by XueRainey** [comment]
你这种建议，难道不应该在你看不惯的网站的问题或建议提交的入口传达给该网站维护者么。 @anlexN

**Comment by BearJ** [comment]
@anlexN 能感觉到你的愤怒与无奈，但是对于发泄，从渠道上来说，[这里会更好](http://support.qq.com/write.shtml)。我来结个贴，并附上我个人的观点：qq.com和一些老的页面，感觉是已经处于维护阶段的产品，它们曾经辉煌过，也承载着我们的一些回忆（我看到qq.com就想起了以前高中时盖着被子偷偷玩手机的时代）。如今，新的项目不断出现，但人力是有限的，把有限的人力投入到新项目的研发中，对于老项目，我们保持一个可用无bug的状态，这不是更好吗？（当然了，说不定哪一天，qq.com就以新项目的形式进行更新~）

**Comment by anlexN** [comment]
@BearJ , 你是好人。我欣赏你。你能把weui多用到腾讯产品，保持一致的风格，能切实实践下去，就更好了。就像Google能把material design设计风格运用到旗下所有产品。
加油！腾讯应该多一点像你这样的谦虚之人！
你的答案，我很满意
