### ISSUE TITLE
launch_3rdApp:fail_invalid signature

### ISSUE THREAD

**Issue by sharp00k** [Tencent/weui#669]
WeixinJSBridge.invoke('launch3rdApp', {
      'appid': 'xxxxxxx',
      'messageExt': 'from=weixin_webview',
      'extInfo': 'from=weixin_webview'
    }, function(e) {
      alert("error" + JSON.stringify(e));
    });

launch_3rdApp:fail_invalid signature

help me

**Comment by BearJ** [comment]
@sharp00k 签名错了，你试着按步骤进行？https://mp.weixin.qq.com/wiki
