### ISSUE TITLE
请问，微信识别二维码后，可以进行回调呢？

### ISSUE THREAD

**Issue by herrdu** [Tencent/weui#670]
请问，微信识别二维码后，可以触发一个回调函数吗？

**Comment by meteorlxy** [comment]
兄弟你问错地方了吧。。

如果是扫公众号二维码的话看[微信公众平台文档](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140454)

扫你自己应用的二维码的话就自己配置呗

**Comment by BearJ** [comment]
楼上正解哈~
