### ISSUE TITLE
input type=“radio” 的标签中的checked元素不会随点击不同的radio而改变

### ISSUE THREAD

**Issue by SalterYu** [Tencent/weui#671]
input type=“radio” 的标签中的checked元素不会随点击不同的radio而改变，例如有两个radio，name分别为r1和r2，我随便选中一个radio后它的checked元素不会变化

**Comment by BearJ** [comment]
radio需要name一致的情况下，才形成组

**Comment by OhTheThree777** [comment]
@BearJ 我的是一样的点上也。。。

**Comment by BearJ** [comment]
您好，看看是否被某些元素遮挡了，或者被某些js逻辑把值又改回来的问题
