### ISSUE TITLE
设置了固定宽度在iphone7上显示不同宽度，在安卓上正常显示

### ISSUE THREAD

**Issue by old-wang** [Tencent/weui#673]
在li 中设置了固定宽度，但是在iphone7上显示出参差不齐的宽度，在安卓和微信开发者工具上正常显示
#count .chart .item .bottom{
  width:27px;
  font-size: 12px;
  background: #bdcdd8;
  color:#fff;
  text-align: center;
  z-index: 9;
  padding:0 2px;
}

**Comment by BearJ** [comment]
看着没啥问题，是不是空白字符导致的？

**Comment by old-wang** [comment]
没有空白字符啊
