### ISSUE TITLE
如何扩展自定义图标字体？

### ISSUE THREAD

**Issue by summer-zeng** [Tencent/weui#676]

**Comment by progrape** [comment]
扩展图表不是非得用字体的，可以有其他方案。转成字体文件可以尝试 [fontello](https://github.com/fontello)

**Comment by summer-zeng** [comment]
你好，谢谢答复，因为想做扩展，那么新的图标需要和原weui的icon融合，能提供weui图标用的svg源文件吗？                             原始邮件                             发件人: jf<notifications@github.com>收件人: Tencent/weui<weui@noreply.github.com>抄送: summer zeng<zengjie618@gmail.com>; Author<author@noreply.github.com>发送时间: 2017年10月16日(周一) 16:19主题: Re: [Tencent/weui] 如何扩展自定义图标字体？ (#676)扩展图表不是非得用字体的，可以有其他方案。转成字体文件可以尝试 fontello

**Comment by BearJ** [comment]
@summer-zeng https://github.com/weui/weui-design 这里有视觉资源，你重新设计后导出svg即可
