### ISSUE TITLE
picker 关闭的时候没有做触发限制~

### ISSUE THREAD

**Issue by deepkolos** [Tencent/weui#678]
popup层关闭的是唯一触发的, 一旦被触发了, 后续触发将会失效~~然后用户急于点击关闭的时候就会出现错误~ 不过幸运的是因为没有做hash状态绑定, 不影响行为~

步骤:
0.点开picker
1.快速多次点击mask

![bug6](https://user-images.githubusercontent.com/12824616/31857536-79191b76-b713-11e7-9777-a8dc2a0a1cf6.gif)

**Comment by BearJ** [comment]
@deepkolos 谢谢，这的确是一个bug

**Comment by BearJ** [comment]
fixed
