### ISSUE TITLE
加载weui.css出现 net::ERR_INCOMPLETE_CHUNKED_ENCODING 错误

### ISSUE THREAD

**Issue by kenziD** [Tencent/weui#681]
在公司内网项目使用了weui.css，直接使用内网加载网页，不会出错，通过外网连接了vpn后加载网页出现，page一直空白，Loadding的图标一直顺时针旋转，很久之后，出现了net::ERR_INCOMPLETE_CHUNKED_ENCODING错误。在加载weui.css时，response header里面有一个transfer-encoding:chunked

**Comment by kenziD** [comment]
![Uploading bug.png]()
在地址栏直接请求这个文件发现，一直卡在最后那句程序，但因为之前怀疑过是由于**data:url**规则造成的问题，所以注释掉了，结果居然还是卡在这里。所以就删掉了所有**data:url**规则加载的字体和图片。然后就完整加载了，不会chunke，供类似问题的童鞋参考，但还是有点迷惑，望大神们指点。。

**Comment by qianduan** [comment]
这个问题和 CSS 文件本身并没有关系，`net::ERR_INCOMPLETE_CHUNKED_ENCODING` 是 HTTP 的错误，`transfer-encoding:chunked` 也是 HTTP 的配置，建议 Google 一下对应的关键词然后 check 一下你服务器的配置，比如NGINX或者Apache的相关配置。
