### ISSUE TITLE
关于命名的缩写

### ISSUE THREAD

**Issue by aristotll** [Tencent/weui#688]
从[维基](https://github.com/Tencent/weui/wiki/Cell)知道

>`cell`由 thumbnail`weui-cell__hd`、body`weui-cell__bd`、accessory`weui-cell__ft`三部分组成，其中`weui-cell__bd`采用自适应布局

**hd** 是啥缩写啊?
bd body
ft footer(?? 不确定

**Comment by asdevo** [comment]
head body footer
