### ISSUE TITLE
weui交流的方式？

### ISSUE THREAD

**Issue by SmallElephant** [Tencent/weui#69]
是否可以考虑给个微信群或者QQ群方便大家的交流，weui才出，最近想使用weui框架，如果有个官方的交流方式更快捷方便一点~

**Comment by progrape** [comment]
感谢 @SmallElephant 的建议，已建立QQ交流群:)

可以通过一下方式加群：

-

**Comment by 444194401** [comment]
已申请

**Comment by jiujiu3178** [comment]
**已申请**
