### ISSUE TITLE
如何适配不同的分辨率

### ISSUE THREAD

**Issue by yuzifu** [Tencent/weui#690]
使用weui写的一个页面，在PC的浏览效果正常，在移动端访问却是字体小的无法接受，请问weui如何适配不同分辨率地屏幕？
![2](https://user-images.githubusercontent.com/853731/33054411-0e653e78-ceb4-11e7-86b8-85d69b6bef51.PNG)
![default](https://user-images.githubusercontent.com/853731/33054416-12ab5562-ceb4-11e7-8f70-688eee93c1ad.PNG)

**Comment by goalidea** [comment]
哈哈，我是新手，来看大神解答
