### ISSUE TITLE
weui-cell:before和weui-cells:before这根线会闪烁

### ISSUE THREAD

**Issue by yuzifu** [Tencent/weui#692]
在一个表单里仿example里dialog实现了一个通知消息框，在弹出和关闭消息框时，表单项下面的那要灰色线（weui-cell:before、weui-cells:before）看起像是闪烁的效果，跟example的效果不一致。仔细看了下，原因是因为开启消息框时这些灰线要消息框完全显示完成后才变黑，而半闭时又提前变灰，就是说这些灰线不能跟同时变化颜色。

**Comment by topcloud-xx** [comment]
我也遇到这个问题了，麻烦从框架层面处理一下呗。谢谢！

**Comment by xiaoyouxi01** [comment]
我去！原来有人提过这个问题啊！我也遇到了，请问楼主后来如何解决的呀？

这个问题不解决，表单就很不好弄。。。

**Comment by BearJ** [comment]
您好，新版已解决这个问题。
