### ISSUE TITLE
WeChat emojis (絵文字)

### ISSUE THREAD

**Issue by Crissov** [Tencent/weui#694]
I was expecting to find WeChat's emoji graphics and codes for them here or in a related repository, so one could use them on the web (outside the app). 

I'm not sure [this comment](https://github.com/Tencent/weui/issues/9#issuecomment-173427019) or issue #383 is asking for the same as I don't understand Chinese, sorry.

**Comment by YWNA** [comment]
[http://www.oicqzone.com/tool/emoji/](ref url)

**Comment by YWNA** [comment]
[refrence url](http://www.oicqzone.com/tool/emoji/)

**Comment by Crissov** [comment]
Um, no, that is an (outdated) reference for Unicode emojis. The column labeled _Wechat_ has the plain Unicode characters which can be used in the WeChat app, but it does not show the custom WeChat graphics or codes.

**Comment by BearJ** [comment]
Maybe this npm module can help you: https://www.npmjs.com/package/qqface
