### ISSUE TITLE
https://weui.io 无法访问

### ISSUE THREAD

**Issue by googol4u** [Tencent/weui#695]
https://weui.io 无法访问

**Comment by linking123** [comment]
同问？这个库还能用吗？

**Comment by zjhui** [comment]
还是少用吧。一堆坑没填。

**Comment by billschen** [comment]
可以访问呀，一直可以。我在用，一般的表单还可以处理。

**Comment by WickedDogg** [comment]
很奇怪，three.js和orbitControls.js竟然报403错误

**Comment by Kennersky** [comment]
访问了，标题变成“2022冬奥有我”，js报错，显示不出来。

**Comment by WickedDogg** [comment]
目测是升级出现问题了，不过冬奥那个现在不显示了，就好了 @linking123
