### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by 396650292** [Tencent/weui#698]
![image](https://user-images.githubusercontent.com/31367685/34548653-33d5237e-f13e-11e7-8fcd-08ed6c05a011.png)

![image](https://user-images.githubusercontent.com/31367685/34548667-48cd6a3e-f13e-11e7-8c92-638de4dd98f8.png)
无法正常显示

**Comment by YuyangGong** [comment]
需要运行本地服务器才能正常预览的。
git clone后，执行下面的操作
```bash
npm install && npm run start
```
如果你只是想本地看效果，而不是改动调试的话，那直接打开`dist`目录下的文件就可以了，`src`下都是未打包编译的源文件.

**Comment by BearJ** [comment]
您好，如楼上所言。
