### ISSUE TITLE
文档能不能更新一下? 1.0和0.4做个区分?

### ISSUE THREAD

**Issue by ash0080** [Tencent/weui#699]
作为一个官方库,这维护质量和力度真心有点懵逼了... 
1.0都出来一年多了

**Comment by BearJ** [comment]
您好，文档在wiki下：https://github.com/Tencent/weui/wiki/%E5%9C%A81.0.0%E5%9C%A8%E4%BB%A3%E7%A0%81%E5%B1%82%E9%9D%A2%E4%B8%8A%E5%81%9A%E4%BA%86%E5%93%AA%E4%BA%9B%E6%94%B9%E5%8F%98
