### ISSUE TITLE
不支持国际化i18n多语言

### ISSUE THREAD

**Issue by mathslimin** [Tencent/weui#700]
没有多语言支持

**Comment by YuyangGong** [comment]
这仅仅只是一个样式库而已呀。能国际化什么呢？weui里面有任何需要国际化的么，所有的label, value, placeholder之类的都是库的使用者自己定义的。
如果想要国际化的话， 一般我们国际化一般分为编译时国际化，运行时国际化。
编译时国际化主要依赖构建工具，根据不同的语言表分别打包生成特定的文件, 如`xxx/en/index.html`, `xxx/cn/index.html`
运行时国际化主要依赖JS动态处理， 仅仅只需原本的一份文件，所有的语言切换根据JS里的某个状态变量。

**Comment by docikaci** [comment]
weui.datePicker  没有地方可以配置多语言， 里面的年月 日   等等

同样有多语言的需求！ 谢谢

**Comment by baidi123** [comment]
有没有提供可以国际化的思路?
前端有这个需求

**Comment by BearJ** [comment]
您好，datePicker目前不支持国际化，只能用户自己传入数组到普通picker来实现。
