### ISSUE TITLE
html文件为什么会写js_之类的类，在css中并未找到

### ISSUE THREAD

**Issue by zhangjuanjuan01** [Tencent/weui#701]
如src/fragment/home.html 中定义了js_category，js_categoryInner，js_item这些类，
但是并没写任何的样式，写这些类的作用是什么?为什么要冗余无用的类在这里？

**Comment by engineerzy** [comment]
您是哪位？


发自网易邮箱 iPhone 版
在2018年01月16日 20:29，zhangjuanjuan01 写道:

如src/fragment/home.html 中定义了js_category，js_categoryInner，js_item这些类，
但是并没写任何的样式，写这些类的作用是什么?为什么要冗余无用的类在这里？

**Comment by zhangjuanjuan01** [comment]
使用weUI的前端开发人员，在看到这个案例之后，对此有疑问，还请解答



zhangjuanjuan@nongfadai.com
 
发件人： zhouyang
发送时间： 2018-01-16 22:16
收件人： Tencent/weui
抄送： zhangjuanjuan01; Author
主题： Re: [Tencent/weui] html文件为什么会写js_之类的类，在css中并未找到 (#701)
您是哪位？


发自网易邮箱 iPhone 版
在2018年01月16日 20:29，zhangjuanjuan01 写道:

如src/fragment/home.html 中定义了js_category，js_categoryInner，js_item这些类，
但是并没写任何的样式，写这些类的作用是什么?为什么要冗余无用的类在这里？

**Comment by YuyangGong** [comment]
用于JS获取类名呀, 都有JS前缀了， 具体也可以看example的源码呀

**Comment by zhangjuanjuan01** [comment]
我是想说……为什么不用既有的类，或者通过data扩展属性的方式取获取元素，而要加一个无用的类，专门用于获取元素



zhangjuanjuan@nongfadai.com
 
发件人： GYY
发送时间： 2018-01-19 22:52
收件人： Tencent/weui
抄送： zhangjuanjuan01; Author
主题： Re: [Tencent/weui] html文件为什么会写js_之类的类，在css中并未找到 (#701)
用于JS获取类名呀, 都有JS前缀了， 具体也可以看example的源码呀

**Comment by YuyangGong** [comment]
行为与样式分离。
