### ISSUE TITLE
mini button 样式有问题

### ISSUE THREAD

**Issue by bluewynn** [Tencent/weui#703]
这里右侧的边框发虚了，几乎看不见

机型：MX6
系统：android 7.1.1

![image](https://user-images.githubusercontent.com/9843147/35321432-e6614dea-0121-11e8-92cc-9590983f0574.png)

**Comment by BearJ** [comment]
您好，在某些机型上的确会有这个问题，是因为屏幕分辨率导致。因此你可以：
- 使用1px的边框代替高清1px线
- 使用新版weui，新版weui没有这条边框
