### ISSUE TITLE
表单内容提交问题

### ISSUE THREAD

**Issue by wusj521** [Tencent/weui#709]
以往使用bootstrap是在form中加入 method="post" action="/login">实现后台程序调用，button 通过type="submit"实现。请问使用使用weui要如何实现，多谢指点！

<body>

    <div class="container">

      <form class="form-signin" method="post" action="/login">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">用户ID</label>
        <input type="text" id="uname" class="form-control" name="uname" placeholder="输入用户ID" required autofocus>
        <label for="inputPassword" class="sr-only">登录密码</label>
        <input type="password" id="pwd" class="form-control" name="pwd" placeholder="登录密码" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" name="autoLogin" value="remember-me"> Remember me
            <a class="btn btn-xs btn-default" href="/loginadd" role="button">新用户</a>
            <a class="btn btn-xs btn-default" href="/loginchange" role="button">改密码</a>
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" onclick="return checkInput()" type="submit">Sign in</button>
        
      </form>

**Comment by billschen** [comment]
一样的实现方法呀，weui不会对此造成影响。

**Comment by BearJ** [comment]
您好，一样的实现方法，只是 html结构 和 类名换成weui的对应的类名

**Comment by wusj521** [comment]
谢谢！
