### ISSUE TITLE
iphone手机点击picker内容跳转页面再返回时，下拉框仍然存在，且点击取消无效

### ISSUE THREAD

**Issue by daijinghao** [Tencent/weui#710]
在弹出的picker下拉框中，选中某个值，确定，跳转到下一页面，再返回时，安卓手机显示正常，picker下拉框仍然需要点击才能再出来，点击之后取消、确定也可以正常使用；
ios手机跳转再返回后，picker下拉框仍然存在，点击取消无反应

**Comment by billschen** [comment]
说实话，最后想些图，说明详细些，想高质量的回答，就必须有高质量的提问~

**Comment by BearJ** [comment]
您好，建议你在跳转前，手动关闭一下picker，picker会返回实例，里面有一个close的方法。
