### ISSUE TITLE
weui.io 页面样式bug

### ISSUE THREAD

**Issue by occultskyrong** [Tencent/weui#712]
### navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"

### 复现
MBP中，将chrome浏览器屏幕高度超过`695px`后
`class = "page__ft j_bottom"`的元素会遮挡住展开的项，
并固定到（伪）页面底部的位置，
并没有随页面的滑动而滚动。

### 截图
![image](https://user-images.githubusercontent.com/8370006/37283995-eb024650-2634-11e8-97a2-c63157a14166.png)
![image](https://user-images.githubusercontent.com/8370006/37284004-f1448c58-2634-11e8-8271-893b5aef7c04.png)

**Comment by BearJ** [comment]
您好，这个bug已fix。不过这是DEMO，只做展示用，不推荐生产环境中使用。
