### ISSUE TITLE
tabbar中添加list，list中的标题文字和说明文字居中对齐了

### ISSUE THREAD

**Issue by michael2043** [Tencent/weui#714]
tabbar中添加list，list中的标题文字和说明文字居中对齐了
怎么能让标题文字和说明文字恢复对齐方式

`<view class="page">
    <view class="page__bd">
        <view class="weui-tab">
            <view class="weui-navbar">
                <block wx:for="{{tabs}}" wx:key="*this">
                    <view id="{{index}}" class="weui-navbar__item {{activeIndex == index ? 'weui-bar__item_on' : ''}}" bindtap="tabClick">
                        <view class="weui-navbar__title">{{item}}</view>
                    </view>
                </block>
                <view class="weui-navbar__slider" style="left: {{sliderLeft}}px; transform: translateX({{sliderOffset}}px); -webkit-transform: translateX({{sliderOffset}}px);"></view>
            </view>
            <view class="weui-tab__panel">
                <view class="weui-tab__content" hidden="{{activeIndex != 0}}">
                  <view class="page__bd">
                    <view class="weui-cells weui-cells_after-title">
                      <view class="weui-cell">
                          <view class="weui-cell__bd">标题文字</view>
                          <view class="weui-cell__ft">说明文字</view>
                      </view>
                    </view>
                  </view>
                </view>
                <view class="weui-tab__content" hidden="{{activeIndex != 1}}">选项二的内容</view>
                <view class="weui-tab__content" hidden="{{activeIndex != 2}}">选项三的内容</view>
            </view>
        </view>
    </view>
</view>`

**Comment by KevinHades** [comment]
你从navbar.wxss直接复制过来的样式里weui-tab__content被覆盖了样式，解决方法weui-tab__content 样式添加或者改成text-align:left
