### ISSUE TITLE
weui-cells和对话框弹窗一起显示时有问题，会有白线，怎么办？

### ISSUE THREAD

**Issue by xiaoyouxi01** [Tencent/weui#718]
![gif](https://user-images.githubusercontent.com/36061058/38619466-cabb50e2-3dce-11e8-9fad-846564ff94f9.gif)

请看上面这个演示动画，我在官方演示文件index.html→操作反馈→Dialog对话框页面→在那4个按钮下面加了一段：

```
	<div class="weui-cells">
	<p>啊啊</p>
	</div>
```

然后点击这几个弹对话框的按钮，会看到weui-cells上下两条白线。。。

这个是BUG吗？请问该如何解决呀？

**Comment by xiaoyouxi01** [comment]
我就只在4个按钮下面加了这样一段代码：
`<div class="weui-cells">
<p>啊啊</p>
</div>`

**Comment by meiyoufengzhengdexian** [comment]
我也碰到了这个问题

**Comment by BearJ** [comment]
您好，新版已fix了这个问题
