### ISSUE TITLE
急需多语言国际化支持，谢谢

### ISSUE THREAD

**Issue by docikaci** [Tencent/weui#720]
其实重点是日期框，其他的组件都可以自定义。

**Comment by docikaci** [comment]
![image](https://user-images.githubusercontent.com/7788102/38714485-0fa1c1a6-3f09-11e8-8053-83a4013125cb.png)

滑动后，日期就会重新渲染，没有地方可以配置文案，
上面确定 和取消 也不支持自定义配置~

picker组件，能完善下吗？
非常感谢

**Comment by billschen** [comment]
这个我想你不要期待了~项目不是很活跃。

**Comment by docikaci** [comment]
@billschen   朋友，有什么方案，建议吗？

**Comment by billschen** [comment]
![myd0255](https://user-images.githubusercontent.com/19528399/38714760-476c56ae-3f0a-11e8-80fc-b3432bf6438e.jpg)
某巴的方案，你自己搜索一下。基于react的，组件比较丰富。你在weui上做扩展，我觉得比较难。

**Comment by BearJ** [comment]
您好，目前无法实现国际化，暂时可以先通过自定义生成的数组放到picker，代替datepicker
