### ISSUE TITLE
图片上传组件三星和vivo手机表现异常

### ISSUE THREAD

**Issue by qinghechaoge** [Tencent/weui#721]
三星手机选择完 图片预览时图片会横过来
vivo手机点击+ 没有反应

**Comment by billschen** [comment]
这个图片上传例子。完全是用html form 做出来的，应该是所有浏览器都支持那个属性，你说的问题不在weui的范围内的问题。

**Comment by daixiangzi** [comment]
楼主解决没，遇到了同样的问题，苹果也是这么个情况

**Comment by BearJ** [comment]
楼上正解，weui只是使用html form而已，各个手机的实现方式不一样，所以无法统一
