### ISSUE TITLE
左滑删除的js官方有没有提供

### ISSUE THREAD

**Issue by a294974783** [Tencent/weui#723]
如题，不知道有没有？

另外网上有一个jQuery WEUI，实现了左滑删除，但他默认把weui改为$ 标识符，和我其他js框架冲突了，有人知道怎么把$变回weui么？

**Comment by SimpleSimple** [comment]
MARK，同样问题

**Comment by wangwudong** [comment]
自己写难度很大吗？

**Comment by yangjisen** [comment]
npm install vue-touch

**Comment by BearJ** [comment]
您好，weui只是提供样式库，js的话可以到weui.js那里去提issue哈
