### ISSUE TITLE
weui在ios下往上滑动会出现浮动层遮挡footer，weui官网也有此问题

### ISSUE THREAD

**Issue by vivayue** [Tencent/weui#729]
在政务微信app上通过扫描二维码打开weui官网https://weui.io/页面，往上滑动的时候，页脚下方出现一个浮动框遮挡页面下方的内容。
截图如下：
![image](https://user-images.githubusercontent.com/11346163/39290562-936c0722-4962-11e8-9ba9-9663214b1af9.png)

**Comment by vivayue** [comment]
通过微信扫一扫不存在此问题，在政务微信app扫一扫就存在此问题

**Comment by BearJ** [comment]
您好，应该是和政务微信app的实现有关，而非weui的问题。
