### ISSUE TITLE
将weui.wxss放到小程序项目根目录下 编译报错：不支持 * 和 ~ 匹配符?????

### ISSUE THREAD

**Issue by ylovely** [Tencent/weui#730]
![image](https://user-images.githubusercontent.com/14031036/39390758-e8bbc838-4acb-11e8-9824-170904a46b58.png)

**Comment by yushaona** [comment]
我也遇到这个问题了，怎么解决的？

**Comment by Sopcce** [comment]
> 如果是做微信小程序,https://github.com/Tencent/weui-wxss 用这个，weui为为web服务用的，不是一个东西

虽然不是一个东西，但是应该兼容支持的吧，腾讯开源的东西和开发的编辑器看来不是一家的，艾
