### ISSUE TITLE
.weui-input 样式坑

### ISSUE THREAD

**Issue by DockerAdminDev** [Tencent/weui#736]
在[`https://weui.io/#input`](https://weui.io/#input)上的例子 @weuiCellHeight: 25px;
![image](https://user-images.githubusercontent.com/39473882/42120281-90635852-7c4b-11e8-8b95-04b02ac3ddf7.png)

但是在源码上 @weuiCellHeight: 44px;
这里影响到了@weuiCellHeightEm: unit(@weuiCellHeight / @weuiCellFontSize, em);
变成这样：
![image](https://user-images.githubusercontent.com/39473882/42120278-73afaee0-7c4b-11e8-85f6-ca646739f0ab.png)

border的颜色也不一样
@weuiCellBorderColor:#F2F2F2; // weui.io上的
@weuiCellBorderColor:#D9D9D9; // 源码的

**Comment by BearJ** [comment]
新版这里做了改变，不再使用 weuiCellHeightEm 了
