### ISSUE TITLE
weui searchBar搜索

### ISSUE THREAD

**Issue by momoangu** [Tencent/weui#737]
微信公众号网页开发，weui的 searchBar的searchInput的输入完内容后，点软键盘的完成键就自动搜索了，我想监听一下这个完成按键的动作自己来写内容，应该如何处理？

**Comment by PL-SQL** [comment]
难受啊 就算捕获到了事件也不能阻止请求发送

**Comment by BearJ** [comment]
您好，可以监听'keypress'事件，判断keycode为13来试试
