### ISSUE TITLE
uploader 在一些手机上，只能默认浏览相册，看不到相机选项

### ISSUE THREAD

**Issue by sunnyQu** [Tencent/weui#738]
在开发公众号页面过程中发现一个问题，不知是不是微信浏览器bug还是uploader设置权限问题
手机型号：华为V8 ，安卓版本7.0
微信版本：6.6.7 (当前最新版本)
html中设置：`<input id="uploaderInput" class="weui-uploader__input " type="file" name="photo" accept="image/*" multiple="">`
现象：在微信中浏览页面，使用uploader选择图片，看不到“相机”选项，直接进入到浏览图片界面；将此链接在该手机上的腾讯浏览器中打开，选择图片，可以看到 “相机”选项
此问题在 红米note4 安卓6 上也有；
微信浏览器bug？ 还是需要特殊设置
望给与建议，谢谢~

**Comment by sunnyQu** [comment]
原因找到了，是微信浏览器未加载x5内核浏览器造成的

**Comment by daixiangzi** [comment]
我也出现了这个问题，请问你是怎么解决的？

**Comment by daixiangzi** [comment]
我之前点击上传控件的时候还可以找到摄像头，现在就找不到了？

**Comment by BearJ** [comment]
您好，现在使用的写法是：
```html
<input id="uploaderInput" class="weui-uploader__input" type="file" accept="image/*" multiple="">
```
