### ISSUE TITLE
picker组件滑动时，底下的页面在滑动

### ISSUE THREAD

**Issue by andrewyoung51** [Tencent/weui#740]
当前使用picker组件，弹出的界面z-index为5000。
当主页面（底下的页面）高度不足一屏时，木有问题。而超过一屏时，滑动就没有那么灵活了。弹出的界面选项没有变化，而底下的页面在上下滑动。

**Comment by hdwong** [comment]
遇到同样的问题，望领导关注。

**Comment by BearJ** [comment]
您好，请到[weui.js](https://github.com/Tencent/weui.js)下去提出issue哈。
