### ISSUE TITLE
Mpvue项目安装WeUi依赖后会报编译错误

### ISSUE THREAD

**Issue by HarreyJia** [Tencent/weui#742]
用npm install安装好WeUi的依赖后进行npm run dev，然后打开微信开发者工具，结果报编译错误。
在weui.css文件中找到三处有波浪线的地方，将其注释后就能编译成功。
请问是.wxss文件已经不支持这种波浪线用法了吗？
![default](https://user-images.githubusercontent.com/42228324/44192593-9c8aa900-a162-11e8-9191-e3ff8223259d.JPG)

**Comment by Charley-liu** [comment]
这个问题你解决了吗？？我现在遇到的问题和你相同，不同版本都试了还是这个问题，程序关闭在重新开还是这个问题

**Comment by BearJ** [comment]
@HarreyJia 小程序有对应的weui库，https://github.com/Tencent/weui-wxss
