### ISSUE TITLE
weui-btn css

### ISSUE THREAD

**Issue by CellOcean** [Tencent/weui#743]
![image](https://user-images.githubusercontent.com/9833678/44318710-50917a00-a46a-11e8-8e24-cd167e2a0d89.png)

请问一下：
这个btn的样式里，把widht和height都设置为200%，然后又通过scale(0.5)，缩小50%。是不是有点问题？

**Comment by uxsi** [comment]
@CellOcean 这是为了实现高清屏上的按钮边框高清效果，2.0版本里面按钮UI有变化，不加边框了
