### ISSUE TITLE
.weui-btn:after {border: ...}引发边框不正常显示的问题

### ISSUE THREAD

**Issue by microkof** [Tencent/weui#749]
由于.weui-btn没有定义border，但是:after定义了border，导致某些情况下，按钮的右边线不显示。

当然，不排除是其他原因导致的问题，因为问题确实很奇怪。下图的某些按钮不能正常显示右边线，某些又可以。

当我把.weui-btn:after 的width改为198%，则正常显示。

![image](https://user-images.githubusercontent.com/5286586/46943804-0c55db00-d0a3-11e8-8f05-f37909d89405.png)

**Comment by BearJ** [comment]
您好，v2.0.1的版本已经把这个边框去掉了。不能正常显示，估计是和屏幕分辨率有关，某些机器当这条高清线刚好处于奇数分辨率的位置的时候，会显示不出来，这时建议改为1px的线，或者使用v2.0.1
