### ISSUE TITLE
dataPicker绑定多个组件方法的问题

### ISSUE THREAD

**Issue by aq82** [Tencent/weui#752]
#labPoBirth,#childrenBirth 这个2个组件都绑定了datePicker组件，
labPoBirth 值为：1991-01-01；
childrenBirth 值为：2018-03-15；
我的操作场景是这样的，

- 首页：点击 labPoBirth 组件，弹出窗口默认显示值为 1991-01-01，之后选择时间  1991-02-01，并确定；
- 接着：点击childrenBirth 组件，这时弹出窗口显示数值是之前的“1991-02-01”，而不是“2018-03-15”；

问题是出现在“onChange”这个方法上，当点击“childrenBirth ”组件时，onChange参数的 result为之前选中的数值。
我希望实现的效果： 当选择“childrenBirth ”时，可以实现弹出窗口数值为“2018-03-15”。这个要如何实现？
以下附上我写的js代码。

> 
   $("#labPoBirth,#childrenBirth").on('click', function () {
        var obj = this;
        var objvalue = this.value;
        if (objvalue != "")
        {
            objvalue = [new Date(this.value).getFullYear(), new Date(this.value).getMonth() + 1, new Date(this.value).getDate()];
        }
        else
        {
            objvalue = [new Date().getFullYear(), new Date().getMonth() + 1, new Date().getDate()];
        }
        var result = objvalue;
        //
        weui.datePicker({
            start: 1990,
            end: new Date().getFullYear(),
            defaultValue: objvalue,
            onChange: function (result) {
                result = objvalue;
                console.log(result);
            },
            onConfirm: function (result) {
                //console.log(result);
                obj.value = (new Date(result).getFullYear()) + "-" + (new Date(result).getMonth() + 1) + "-" + (new Date(result).getDate());
            }
        });
    });

**Comment by kissmybaby52** [comment]
2个组件分别绑定datePicker，并且参数一定要加id，不写id或者2个控件绑定同一个datepicker，操作会相互影响

**Comment by BearJ** [comment]
楼上正解
