### ISSUE TITLE
哪里能找到weui对接微信小程序的文档？

### ISSUE THREAD

**Issue by fishenal** [Tencent/weui#757]
如题，比如<i class="weui-success weui-icon_msg"></i> 好像就不生效，还有所有的div转成view就行吗，好像也不是，小程序也没做weui的文档啊，这是两个独立的部门各干各的？

**Comment by ZMDreamer** [comment]
You can find it on https://developers.weixin.qq.com/miniprogram/dev/devtools/new.html

**Comment by fishenal** [comment]
> You can find it on https://developers.weixin.qq.com/miniprogram/dev/devtools/new.html

文档对样式的描述非常的不详尽，不过可以在 https://github.com/Tencent/weui-wxss/tree/master/src/example  这里找到所有组件样式的使用样例。
