### ISSUE TITLE
IOS微信6.7.4 文本框或输入框调出输入法，退出输入法后，底部会多出一部分。（QQ浏览器内不会复现）

### ISSUE THREAD

**Issue by pkkgu** [Tencent/weui#758]
如题如图

![_20181213093641](https://user-images.githubusercontent.com/3060631/49909814-57ca1100-febb-11e8-9eab-d2d8fcef80aa.jpg)

**Comment by pkkgu** [comment]
`$("input,select,textarea").blur(function(){
	setTimeout(() => {
	const scrollHeight = document.documentElement.scrollTop || document.body.scrollTop || 0;
	window.scrollTo(0, Math.max(scrollHeight - 1, 0));
	}, 100);
})`

暂时解决办法，应该是IOS微信6.7.4和IOS12问题

**Comment by xiedandan** [comment]
我也想来反馈，，跟腾讯客服反馈这个问题，客服就只会复制 粘贴来回答我。。现在7版本了，还是有这问题，，真让人 蛋疼，

**Comment by pompeii666** [comment]
> > $("input,select,textarea").blur(function(){
> > setTimeout(() => {
> > const scrollHeight = document.documentElement.scrollTop || document.body.scrollTop || 0;
> > window.scrollTo(0, Math.max(scrollHeight - 1, 0));
> > }, 100);
> > })
> 
> 暂时解决办法，应该是IOS微信6.7.4和IOS12问题

非常感谢

**Comment by TomLiu-GitHub** [comment]
是啊,这个问题很蛋疼啊.微信ui不支持微信浏览器,说出去别人都不信.

**Comment by BearJ** [comment]
您好，请到[微信开放社区](https://developers.weixin.qq.com/)提出这个问题哈。

**Comment by hlipeter** [comment]
IOS  系统版本 12.2 和 12.4.1 、微信版本：7.08  依然存在问题，特来打卡！
