### ISSUE TITLE
请问是否有计划与微信7.0的样式同步？

### ISSUE THREAD

**Issue by herock** [Tencent/weui#760]
微信7.0的设计语言与之前的版本有非常大的变化，小程序或公众号如果继续使用之前的样式，在微信中会显得陈旧，不知是否有计划做同步？

**Comment by huangmengqi** [comment]
没有

**Comment by herock** [comment]
> 没有

比较遗憾，但谢谢。

**Comment by banricho** [comment]
> > 没有
> 
> 比较遗憾，但谢谢。

他好像并不是官方成员……
不过 WeUI 的确很久没更新了……

**Comment by zhangolve** [comment]
我也想问这个问题来着。

**Comment by qinmingyuan** [comment]
觉得 weui 是微信生态很重要的一部分，可是官方这个态度。。
心里很想说一句 mmp

**Comment by BearJ** [comment]
@herock @qinmingyuan 正在开发中，感谢关注

**Comment by cipchk** [comment]
@BearJ  能否考虑释放 alpha 或 beta 版本

**Comment by BearJ** [comment]
@cipchk 目前还在内部开发中，能测试或体验了将会第一时间在这里公布

**Comment by Anricx** [comment]
provide vue support?

**Comment by uxsi** [comment]
[WeUI 2.0](https://weui.io) 已适配了微信客户端7.0的UI规范，详细请查看[CHANGELOG](https://github.com/Tencent/weui/blob/master/CHANGELOG.md)

**Comment by qinmingyuan** [comment]
感谢官方，解决了心病
