### ISSUE TITLE
picker defaultValue 动态改变,不生效;

### ISSUE THREAD

**Issue by wsxc451** [Tencent/weui#761]
https://blog.csdn.net/wsxc451/article/details/85403909

我这里做的是四色球的设计.每次点击随机生成一注,发行defaultValue不会自动变化,看到源码发行

他们使用了temp[option.id]缓存了上次的defaultValue,导致,动态设置defaultValue 不会自动渲染;

所以我们让id每次都不同,那么,他就没有缓存了.每次defaultValue更改,都会及时的生效;!!!
--------------------- 
作者：Oneshop商城 
来源：CSDN 
原文：https://blog.csdn.net/wsxc451/article/details/85403909 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by qichhhhh** [comment]
![image](https://user-images.githubusercontent.com/24191302/50578308-34b7cf00-0e73-11e9-9f82-138c939429f7.png)
Wiki 里已经写的很清楚了…
