### ISSUE TITLE
搜索框组件的代码不全

### ISSUE THREAD

**Issue by zebracmz** [Tencent/weui#764]
还需要jquery！

					<div class="weui-search-bar" id="searchBar">
						<form class="weui-search-bar__form">
							<div class="weui-search-bar__box">
								<i class="weui-icon-search"></i> <input type="search"
									class="weui-search-bar__input" id="searchInput"
									placeholder="搜索" required /> <a href="javascript:"
									class="weui-icon-clear" id="searchClear"></a>
							</div>
							<label class="weui-search-bar__label" id="searchText"> <i
								class="weui-icon-search"></i> <span>搜索</span>
							</label>
						</form>
						<a href="javascript:" class="weui-search-bar__cancel-btn"
							id="searchCancel">取消</a>
					</div>
					<div class="weui-cells searchbar-result" id="searchResult">
						<div class="weui-cell weui-cell_access">
							<div class="weui-cell__bd weui-cell_primary">
								<p>实时搜索文本</p>
							</div>
						</div>
						<div class="weui-cell weui-cell_access">
							<div class="weui-cell__bd weui-cell_primary">
								<p>实时搜索文本</p>
							</div>
						</div>
						<div class="weui-cell weui-cell_access">
							<div class="weui-cell__bd weui-cell_primary">
								<p>实时搜索文本</p>
							</div>
						</div>
						<div class="weui-cell weui-cell_access">
							<div class="weui-cell__bd weui-cell_primary">
								<p>实时搜索文本</p>
							</div>
						</div>
					</div>
				</div>
				<div class="page__ft">
					<a href="javascript:home()"><img
						src="./images/icon_footer_link.png" /></a>
				</div>
			</div>
			<script type="text/javascript">
				$(function() {
					var $searchBar = $('#searchBar'), $searchResult = $('#searchResult'), $searchText = $('#searchText'), $searchInput = $('#searchInput'), $searchClear = $('#searchClear'), $searchCancel = $('#searchCancel');

					function hideSearchResult() {
						$searchResult.hide();
						$searchInput.val('');
					}
					function cancelSearch() {
						hideSearchResult();
						$searchBar.removeClass('weui-search-bar_focusing');
						$searchText.show();
					}

					$searchText.on('click', function() {
						$searchBar.addClass('weui-search-bar_focusing');
						$searchInput.focus();
					});
					$searchInput.on('blur', function() {
						if (!this.value.length)
							cancelSearch();
					}).on('input', function() {
						if (this.value.length) {
							$searchResult.show();
						} else {
							$searchResult.hide();
						}
					});
					$searchClear.on('click', function() {
						hideSearchResult();
						$searchInput.focus();
					});
					$searchCancel.on('click', function() {
						cancelSearch();
						$searchInput.blur();
					});
				});
			</script>
-->

**Comment by BearJ** [comment]
您好，我们还有一个[weui.js](https://github.com/Tencent/weui.js)的配合使用。

**Comment by zebracmz** [comment]
解决很久了，不仅仅是js文件的问题。所有示例全部挤在一个页面，要用的话还要翻源代码，然后复制出来，不方便
