### ISSUE TITLE
【拓展组件】日期事件无法js更新值

### ISSUE THREAD

**Issue by weijiawei** [Tencent/weui#767]
比如我有开始时间和结束时间，我选了结束时间，在关闭的时候想默认设置开始时间，发现怎么也设置不上，用picker的setValue跟进源码是cols为空（明显为空，日期是一级又不是多级），用datetimePicker的input参数也不行，没效果，请马上解决

**Comment by BearJ** [comment]
@weijiawei 再次打开的时候可以使用一个新的id试试

**Comment by weijiawei** [comment]
多谢大佬，当时事急从权，我选择了手写。
