### ISSUE TITLE
Can you provide a gird component which with 4 cells (2x2)

### ISSUE THREAD

**Issue by cmoseses** [Tencent/weui#771]
Your Gird component only support 9 cells now, Can you provide a gird component which with 4 cells?

**Comment by BearJ** [comment]
@cmoseses Like this ?
![image](https://user-images.githubusercontent.com/2395166/62538606-cbbf8c00-b885-11e9-86d2-ba0ac28e8857.png)

**Comment by cmoseses** [comment]
2x2

**Comment by BearJ** [comment]
@cmoseses em....maybe you can 2x2 like this with weui v2.0.1
![image](https://user-images.githubusercontent.com/2395166/64168511-47f5c100-ce7e-11e9-8352-389621bcbd70.png)

**Comment by cmoseses** [comment]
Thanks a lot!
