### ISSUE TITLE
关于weui其他仓库更新的建议

### ISSUE THREAD

**Issue by weihongyu12** [Tencent/weui#781]
我认为 WeUI 应该是一套微信的设计语言，作为官方仓库应该考虑到整个生态

目前仅仅更新了weui一个项目，但是除了此项目，还有如下仓库并未进行更新：

- [weui.js](https://github.com/Tencent/weui.js) WeUI 的轻量级 js 封装
- [react-weui](https://github.com/weui/react-weui) WeUI for React
- [weui-wxss](https://github.com/Tencent/weui-wxss) WeUI for 小程序 
- [weui-design](https://github.com/weui/weui-design) WeUI 设计资源文件

此项目更新的时间较长，即便是绩效项目，我认为也应该做的整个生态完善

**Comment by BearJ** [comment]
@weihongyu12 weui-wxss已更新：https://github.com/Tencent/weui-wxss
