### ISSUE TITLE
weui实现多层级的展开和收起

### ISSUE THREAD

**Issue by xiaobu1994** [Tencent/weui#784]
![https://weui.io](http://wx3.sinaimg.cn/large/0062Ue2Wgy1g37t8oqn64j30dc0m8jxu.jpg)

我想要达到这一的效果但是没有找到相应的demo；请大佬指点一下。

**Comment by BearJ** [comment]
@xiaobu1994 WeUI目前还没有这种组件，所以只能自己实现了。要说样式最接近的，当属weui-cells了

**Comment by xiaobu1994** [comment]
嗯嗯 感谢大佬
