### ISSUE TITLE
datePicker出来的不是当前日期

### ISSUE THREAD

**Issue by kaizi311** [Tencent/weui#786]
版本为1.1.2
    this.$weui.datePicker({
                    start:1940,
                    end:2050,
                    onConfirm:function(result){
                        let years = result[0].value
                        let momth = result[1].value
                        let day = result[2].value
                        if(momth<10){
                            momth = '0'+ result[1].value
                        }
                        if(day<10){
                            day = '0'+ result[2].value
                        }
                        _this.startDate = years+'-'+momth+'-'+day
                    },
                    id:'startPicker'
                })

**Comment by BearJ** [comment]
@1101451024 是不是样式有修改过？导致字体的大小改变了？
