### ISSUE TITLE
小白 想问下panel怎么自定义高度以适应weui-media-box__desc中更多地文本？

### ISSUE THREAD

**Issue by imzhanghee** [Tencent/weui#789]
小白 想问下panel怎么自定义高度以适应weui-media-box__desc中更多地文本？

**Comment by AaronChengHao** [comment]
了解下 line-clamp 这个属性， 可以控制显示的行数

**Comment by imzhanghee** [comment]
> 了解下 line-clamp 这个属性， 可以控制显示的行数

好的，谢谢
