### ISSUE TITLE
comfirm 关闭时 alert 组件无法显示

### ISSUE THREAD

**Issue by yyh2219182230** [Tencent/weui#791]
在使用 comfirm 组件的时候，在确定的回调事件触发时，调用 weui.alert 无法显示

```
weui.confirm('重新提交...', function(){
    weui.alert('再来一次');
});
```

alert 弹框 不会出现。

**Comment by yangjisen** [comment]
```
weui.confirm('重新提交...', function(){
    setTimeout( ()=>{weui.alert('再来一次');}
});
```

**Comment by yyh2219182230** [comment]
你们这个bug不准备修复吗？




------------------ 原始邮件 ------------------
发件人: "yangjisen"<notifications@github.com>; 
发送时间: 2019年8月2日(星期五) 下午3:20
收件人: "Tencent/weui"<weui@noreply.github.com>; 
抄送: "迟暮 indulgeヽ"<2219182230@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Tencent/weui] comfirm 关闭时 alert 组件无法显示 (#791)



weui.confirm('重新提交...', function(){     setTimeout( ()=>{weui.alert('再来一次');} });

**Comment by BearJ** [comment]
@yyh2219182230 后面会修复，目前可以先这样解决：
```
var confirm = weui.confirm('重新提交...', function(){
    confirm.hide(function(){ weui.alert('再来一次'); });
});
```

**Comment by yyh2219182230** [comment]
后面又遇到一个 loading组件的问题，如果响应请求过快，load无法关闭。


var load = weui.loading('正在载入...');
.....
$.ajax(..., function(){
      load.hide(function(){             load = weui.loading('正在定位...');
      });
      ....
      $.ajax(....., function(){
              load.hide();   //在这一步的时候，页面的load弹框无法关闭。
      });
});




------------------ 原始邮件 ------------------
发件人: "bear"<notifications@github.com>; 
发送时间: 2019年8月5日(星期一) 晚上7:42
收件人: "Tencent/weui"<weui@noreply.github.com>; 
抄送: "迟暮 indulgeヽ"<2219182230@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Tencent/weui] comfirm 关闭时 alert 组件无法显示 (#791)




@yyh2219182230 后面会修复，目前可以先这样解决：
 var confirm = weui.confirm('重新提交...', function(){     confirm.hide(function(){ weui.alert('再来一次'); }); });
