### ISSUE TITLE
更新最新weui2.1.2版界面直接错乱了

### ISSUE THREAD

**Issue by zuoyifeng** [Tencent/weui#809]
`.weui-cells_form .weui-cell__bd {
    display: -webkit-box;
    display: -webkit-flex;
    display: flex;
}`
因为这个代码flex布局有问题 上传图片添加按钮直接第二行

**Comment by uxsi** [comment]
@zuoyifeng  谢谢反馈，可以先对`weui-uploader`加一个`flex:1`或者`width:100%`，我们在下个版本修复

**Comment by zuoyifeng** [comment]
> @zuoyifeng 谢谢反馈，可以先对`weui-uploader`加一个`flex:1`或者`width:100%`，我们在下个版本修复

OK thx

**Comment by uxsi** [comment]
@zuoyifeng v2.1.3已修复
