### ISSUE TITLE
安卓手机上传图片预览有问题

### ISSUE THREAD

**Issue by zuoyifeng** [Tencent/weui#812]
https://weui.io/#uploader
用安卓手机打开这个页面 发现上传后点击图片预览 只有一个删除图标 都没预览的该图片
经查验发现由于样式env(safe-area-inset-left);这种写法是不是不识别还是什么原因
请提供解决方案谢谢

**Comment by zuoyifeng** [comment]
是为了适配iphonex吗？但是你没有用媒介查询隔离啊

**Comment by BearJ** [comment]
@zuoyifeng 我用安卓机试了下，发现是可以预览的，你是什么型号呢？

**Comment by zuoyifeng** [comment]
> @zuoyifeng 我用安卓机试了下，发现是可以预览的，你是什么型号呢？
现在好像可以了 是不是因为微信更新了？
我之前测所有安卓都有问题

**Comment by BearJ** [comment]
> > @zuoyifeng 我用安卓机试了下，发现是可以预览的，你是什么型号呢？
> > 现在好像可以了 是不是因为微信更新了？
> > 我之前测所有安卓都有问题

不排除是微信浏览器内核更新了。但建议最好多用一些设备进行测试。

**Comment by zuoyifeng** [comment]
多设备测试对我没有 意义 我只要发现问题 就可以提交 我不是这个框架开发者
