### ISSUE TITLE
upload上传图片后预览

### ISSUE THREAD

**Issue by zuoyifeng** [Tencent/weui#813]
upload上传图片后 打开上传图片预览 【安卓手机】返回按钮会直接关闭整个当前页面 而不是关闭弹出的图片的预览 这个不知道有没有可以优化改良的地方呢？？？
因为既然做了这个效果肯定要用的吧 对不对

**Comment by BearJ** [comment]
@zuoyifeng 是的，这里只是作为一个展示的DEMO，所以细节就没有深究。更严谨的话，是应该通过hash来控制这个预览的显示与否，这样就可以妥善地返回按钮了。
