### ISSUE TITLE
ios13微信内置webview内动画部分失效

### ISSUE THREAD

**Issue by wen911119** [Tencent/weui#815]
ios版本：13.1.2
机型：iPhone 7p
微信版本：7.0.8

复现步骤：
1. 在微信内打开weui的演示网页https://weui.io/weui.js/
2. 点击ActionSheet，可以看到actionsheet弹出时动画失效

**Comment by wen911119** [comment]
神奇的是，今天竟然一切正常了。没有升级系统，也没有更新微信。难道微信用的热更新修复的？

**Comment by erbing** [comment]
同样和楼上的情况一样，有同学有解决方案么？
