### ISSUE TITLE
iphone se上，picker显示有问题

### ISSUE THREAD

**Issue by fengshengchang** [Tencent/weui#816]
1、左上角的关闭符合“X”，显示位置不正确
2、底下的确认按键不显示

**Comment by BearJ** [comment]
@fengshengchang 方便提供一下截图不？

**Comment by lwl8855** [comment]
我也发现这个问题  
![lALPBE1XYgK_1UnNBHDNAoA_640_1136](https://user-images.githubusercontent.com/26382067/67449876-35159680-f64e-11e9-9c6c-ce228453bb8c.png)

**Comment by BearJ** [comment]
@lwl8855 关闭的位置在设计上就是那个位置的。至于确定按钮没出现，看看是否没有加上按钮的相关代码？
![image](https://user-images.githubusercontent.com/2395166/68119848-c3d3be80-ff3e-11e9-8b72-bc22f560d7bc.png)

**Comment by fengshengchang** [comment]
@BearJ 网页的模拟的手机页面显示是正常的，但是iphone se手机显示就是有问题的，其他手机显示是正常的，所以确定键的代码是有添加的，这个应该是CSS设置的有些小问题
![image](https://user-images.githubusercontent.com/14884481/68913380-0b0b4c00-0796-11ea-9c93-43f09b1e9f63.png)

**Comment by fengshengchang** [comment]
@BearJ 你拿个真实的iPhone se，打开https://weui.io  里的picker，看下就知道了

**Comment by BearJ** [comment]
确实是bug，我们下个版本修复下。

**Comment by amyzhaotcard** [comment]
@fengshengchang 请问这种情况 你最后怎么处理的呀？

**Comment by BearJ** [comment]
@amyzhaotcard 新版本已修复，可以试试。若不接入新版本，可以针对小屏机，把`weui-half-screen-dialog`的`max-height`设为`none`
