### ISSUE TITLE
weui 会出桌面版的吗，喜欢公众平台的 ui 风格

### ISSUE THREAD

**Issue by mefedev** [Tencent/weui#817]
以后会出么？想 移动端 和 桌面端保持一致的风格

**Comment by huanghe2015** [comment]
大概率不会，因为微信就是为移动而生的。你看网页版和桌面版就知道了，那只是顺手做的。

**Comment by mefedev** [comment]
这样么，其实我也只是希望能统一风格，不然后台一种，移动端一种，桌面端又是一种，个人开发，没有 ui 设计，好乱的感觉

**Comment by huanghe2015** [comment]
不要放弃啊！reopen issue。
