### ISSUE TITLE
单页面 “复制链接”始终为初始地址的问题

### ISSUE THREAD

**Issue by wsxgs** [Tencent/weui#820]
是否可以把复制链接开一个桥方法，或者直接把复制链接和分享的sdk合并传一个复制链接的url

history模式在微信跳转链接无法复制最新链接  这个我看有解决方案，我的需求是页面有一个切换，切换后页面对应为切换后的内容，只是用pushState改变了url并没有跳转路由，我希望用户复制的是新的链接

**Comment by BearJ** [comment]
@wsxgs 这个可以到开发者社区提出哈，https://developers.weixin.qq.com/
