### ISSUE TITLE
uploader 上传的图片在微信PC 客户端和一些手机型号中打开黑屏

### ISSUE THREAD

**Issue by caidi93** [Tencent/weui#824]
使用微信PC 端 打开链接 https://weui.io/#uploader 上传一张图片 点击放大打开时是黑屏的，这个问题也出现在一些华为手机上

**Comment by BearJ** [comment]
![image](https://user-images.githubusercontent.com/2395166/69126236-aed06100-0ae2-11ea-90ff-2f29431406c4.png)

@caidi93 用的是blob协议显示的图片，可能有些浏览器因为隐私问题导致不能以这种方式打开图片。你可以改一下显示方式，用base64来显示也可。
