### ISSUE TITLE
运行npm install 报错

### ISSUE THREAD

**Issue by liuyonghu** [Tencent/weui#826]
`npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tencent%2ftslint-config-wxapp - Not found
npm ERR! 404 
npm ERR! 404  '@tencent/tslint-config-wxapp@0.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'weui-miniprogram'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuyonghu/.npm/_logs/2019-11-26T09_12_25_171Z-debug.log`

**Comment by liuyonghu** [comment]
npm 安装很多包也都被弃用了，什么时候可以更新下

**Comment by BearJ** [comment]
@liuyonghu 这个不是weui.css的问题，要不在这里提下issue？https://github.com/wechat-miniprogram/weui-miniprogram/issues
