### ISSUE TITLE
华为手机上picker的关闭按钮位置有问题

### ISSUE THREAD

**Issue by chunge6336** [Tencent/weui#832]
华为手机上picker的关闭按钮位置有问题
![image](https://user-images.githubusercontent.com/13133496/72677128-f4ee7480-3ad3-11ea-9fbf-d3e88225e55d.png)
机型荣耀play emui9、荣耀10 emui10
可能别的华为手机也这样

**Comment by chunge6336** [comment]
猜测是
padding: 0 calc(24px + env(safe-area-inset-right)) env(safe-area-inset-bottom) calc(24px + env(safe-area-inset-left));
这个css影响的

**Comment by BearJ** [comment]
@chunge6336 收到，我们查一下

**Comment by uxsi** [comment]
@chunge6336 我们用荣耀10 emui10没有复现这个问题，可以麻烦你用能复现的机器打开下面两个页面并提供下截图给我们不？
1. [weui文章组件](https://weui.io/#article)
2. [安全区域测试页面](https://qvqmt.csb.app/)

**Comment by chunge6336** [comment]
这边测试也正常了，应该是华为的bug他们修了
