### ISSUE TITLE
为何要隐藏小型的图标？

### ISSUE THREAD

**Issue by SmallOyster** [Tencent/weui#839]
https://github.com/Tencent/weui/blob/f8ba88106afd027a835397b43ce8b097a429fef5/dist/example/index.html#L2255

想问问为什么要把那几个小size的图标注释掉，不显示出来？

而我看了一下WeUI for Work，那里的icon又是有这种小size的哦~

**Comment by BearJ** [comment]
@SmallOyster 因为小型图标后续将会统一整理在[这个项目](https://github.com/weui/weui-icon)里，weui只保留最常用的几个图标：

**Comment by SmallOyster** [comment]
哦哦，看了一下那里确实挺多图标耶，谢谢了啦~
