### ISSUE TITLE
请问下官方文档地址是多少呢

### ISSUE THREAD

**Issue by is-liyiwei** [Tencent/weui#845]
请问下官方文档地址是多少呢

**Comment by is-liyiwei** [comment]
wiki打开的是404页面

**Comment by BearJ** [comment]
@is-liyiwei 你好，404的问题已修复

**Comment by koran74557** [comment]
四月视频也404了
https://user-images.githubusercontent.com/104236719/164820448-f9b234ea-3ca8-488d-a89f-c94e4e0e0988.mp4
