### ISSUE TITLE
有点神奇，文档地址就是演示地址，第一次见这种操作。

### ISSUE THREAD

**Issue by vobear** [Tencent/weui#847]

**Comment by BearJ** [comment]
@vobear 因为weui本身只是纯css库，所有状态都在演示地址列出来了，开发者要使用对应的组件样式，查看对应的类名即可。

**Comment by ParryQiu** [comment]
这 issue 的问题一点都不克制，官网要链接干什么？
开发人员不会自己找吗？
微信的精髓不就是「克制」嘛。

**Comment by koran74557** [comment]
是的 需要克制

https://user-images.githubusercontent.com/104236719/164825067-dcb2150c-00aa-4822-9b26-a6b0074a69b0.mp4
