### ISSUE TITLE
picker在微信开发者工具上选项经常不能滑动

### ISSUE THREAD

**Issue by BennyPan** [Tencent/weui#852]
手机上正常，开发者工具偶尔可以

**Comment by BearJ** [comment]
@BennyPan 小程序上的picker是使用的小程序原生的picker，或者可以到开发者社区去提一下？https://developers.weixin.qq.com/community/develop/mixflow

**Comment by BennyPan** [comment]
你好，
是在微信开发者工具上调试H5，不是小程序




------------------&nbsp;Original&nbsp;------------------

**Comment by BearJ** [comment]
@BennyPan 那应该是小程序工具上滑动的实现能力和浏览器有区别而导致的问题
