### ISSUE TITLE
weui深色模式有BUG呀！

### ISSUE THREAD

**Issue by long0185** [Tencent/weui#876]
![311610337710_ pic](https://user-images.githubusercontent.com/44433602/104146200-d8de9400-5404-11eb-9c7a-9251a85e86c3.jpg)
![321610337730_ pic](https://user-images.githubusercontent.com/44433602/104146203-daa85780-5404-11eb-954a-c08aa24ee1c5.jpg)
如图，侧面和底部会有流白

**Comment by uxsi** [comment]
@long0185 这是哪个页面？发下url呢？
