### ISSUE TITLE
dialog组件标题出现异常边框，审查元素未发现相关css样式

### ISSUE THREAD

**Issue by world-he** [Tencent/weui#902]

**Comment by world-he** [comment]
开发工具中点击dialog组件标题显示黑色边框，微信小程序里直接显示黄色边框，weui中找不到相关逻辑和样式

**Comment by chenhuaibin** [comment]
同样遇到，解决了吗

**Comment by chenhuaibin** [comment]
![image](https://user-images.githubusercontent.com/52914598/159437889-aee2c6f0-9155-44ad-bb89-dd46381325a2.png)

**Comment by chenhuaibin** [comment]
同样遇到这个问题
![image](https://user-images.githubusercontent.com/52914598/159438052-8a4c2f17-6e71-4a35-8aa6-5cd62f7f9117.png)

**Comment by chenhuaibin** [comment]
同样遇到：开发工具点击标题会显示和消失黑框，真机是黄色框
![image](https://user-images.githubusercontent.com/52914598/159438493-aaeecc89-6a19-4523-8843-e9ec50ce7a5d.png)

**Comment by suijiacai2016** [comment]
你才是陌生人呐，你才是个人。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月22日(周二) 下午4:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Tencent/weui] dialog组件标题出现异常边框，审查元素未发现相关css样式 (Issue #902)




 
同样遇到：开发工具点击标题会显示和消失黑框，真机是黄色框

**Comment by uxsi** [comment]
@world-he @chenhuaibin 你们指的是[小程序组件库](https://github.com/wechat-miniprogram/weui-miniprogram)吧，可以试试升级到最新版
