### ISSUE TITLE
demo中的js框架该用哪个？

### ISSUE THREAD

**Issue by leafship** [Tencent/weui#917]
【背景：】
我用的weui版本：https://res.wx.qq.com/t/wx_fed/weui-source/res/2.5.9/weui.min.css
我照着github weui wiki（https://github.com/Tencent/weui/wiki）里”组件列表“的”代码“中的例子copy到我的项目中。
看wiki中例子代码中的js，好像用的是jquery，所以我又引入了jquery库：https://libs.baidu.com/jquery/1.11.3/jquery.min.js
【问题：】
但我在使用toptips时，照着例子写得js代码，这个toptips并不会显示。

关键代码：
`<div role="alert" id='topTips' class="weui-toptips weui-toptips_warn js_tooltips" style="opacity: 0; display: none;">错误提示</div>`

$tooltips.fadeIn(100); //这句代码，正常情况会让toptips显示，实际上不会。

【分析：】
我怀疑是jquery的fadeIn方法没起到预期效果，然后找官网demo（https://weui.io/#top-tips）例子看，发现引入的是zepto库，我把jquery库改成https://weui.io/zepto.min.js，发现就能正常显示toptips了。

【咨询：】
所以，我想问的是，wiki例子和demo中的js库到底用的是哪个？是zepto吗？那版本是什么？不同weui版本对应的js库版本是什么？
我想要的很简单，就是照着wiki例子或demo，copy进项目的代码所有功能都是正常的，到底该引入哪些依赖的css和js及版本。

**Comment by uxsi** [comment]
@leafship 目前demo使用的是zepto 1.2.0，需要的话可以参考。我们对weui.css的定位只是一个组件样式库，和前端的技术栈没有耦合。另外我们也提供了一个带功能的[weui.js](https://github.com/Tencent/weui.js)，但由于维护成本，两边的组件不一定及时同步。
