### ISSUE TITLE
tabbar的示例代码和示例的效果不符

### ISSUE THREAD

**Issue by leafship** [Tencent/weui#919]
我直接把示例代码（https://github.com/Tencent/weui/blob/master/src/example/tabbar/tabbar.html）拷贝到我的项目里，

期望效果：（官网demo所示截图）：
[
![image](https://user-images.githubusercontent.com/99376969/183589100-26ea73a7-89be-4f3a-b11f-fce193d9180c.png)
](url)

实际效果（我项目呈现的效果）：
[
![image](https://user-images.githubusercontent.com/99376969/183589456-ff37e1fb-1da9-4afa-8e04-86054b54627e.png)
](url)

是不是示例代码不对啊？照样拷贝过去的，可是效果就不一样。求官方给出示例代码之前，能不能都测一下，达到拷贝即可用的成都。我都花了半天时间调试了，也没调好，也不知道哪里不对，太耽误时间浪费生命了。

**Comment by uxsi** [comment]
@leafship 你的页面是小程序，参考[weui-wxss](https://github.com/Tencent/weui-wxss)，另外就算是网页，一个包含完整样式的组件也可能会因为实际页面的上下文样式受影响，出现什么样的问题得看具体的使用场景
